-- AlterTable
ALTER TABLE `appointments` ADD COLUMN `endAt` DATETIME(3) NULL,
    ADD COLUMN `isBlocker` BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN `location` VARCHAR(191) NULL,
    ADD COLUMN `note` TEXT NULL,
    ADD COLUMN `reminder15m` BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN `reminder1h` BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN `reminder24h` BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN `startAt` DATETIME(3) NULL,
    ADD COLUMN `taskId` VARCHAR(191) NULL,
    ADD COLUMN `title` VARCHAR(191) NULL,
    ADD COLUMN `type` ENUM('CITA', 'RECOGIDA', 'ENTREGA', 'LLAMADA', 'MANTENIMIENTO', 'PRUEBA_RUTA', 'OTRO') NOT NULL DEFAULT 'CITA',
    MODIFY `vehicleId` VARCHAR(191) NULL,
    MODIFY `customerId` VARCHAR(191) NULL;

-- AddForeignKey
ALTER TABLE `appointments` ADD CONSTRAINT `appointments_taskId_fkey` FOREIGN KEY (`taskId`) REFERENCES `tasks`(`id`) ON DELETE SET NULL ON UPDATE CASCADE;
