-- AlterTable
ALTER TABLE `vehicles` MODIFY `status` ENUM('RECEIVED', 'IN_PROGRESS', 'WAITING_PARTS', 'COMPLETED', 'DELIVERED', 'RECEPCION', 'INGRESO', 'DIAGNOSTICO', 'COTIZACION_APROBACION', 'PROCESO_DESARME', 'ESPERA', 'PROCESO_ARMADO', 'PRUEBA_CALIDAD', 'ENTREGA') NOT NULL DEFAULT 'RECEIVED';

-- CreateTable
CREATE TABLE `workflow_status` (
    `id` VARCHAR(191) NOT NULL,
    `vehicleId` VARCHAR(191) NOT NULL,
    `status` ENUM('RECEIVED', 'IN_PROGRESS', 'WAITING_PARTS', 'COMPLETED', 'DELIVERED', 'RECEPCION', 'INGRESO', 'DIAGNOSTICO', 'COTIZACION_APROBACION', 'PROCESO_DESARME', 'ESPERA', 'PROCESO_ARMADO', 'PRUEBA_CALIDAD', 'ENTREGA') NOT NULL,
    `technicianId` VARCHAR(191) NULL,
    `notes` TEXT NULL,
    `timestamp` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `workflow_status` ADD CONSTRAINT `workflow_status_vehicleId_fkey` FOREIGN KEY (`vehicleId`) REFERENCES `vehicles`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `workflow_status` ADD CONSTRAINT `workflow_status_technicianId_fkey` FOREIGN KEY (`technicianId`) REFERENCES `users`(`id`) ON DELETE SET NULL ON UPDATE CASCADE;
